name: Build and Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      staging_environment:
        type: choice
        description: Choose Staging Environment
        options:
          - stage1
          - stage2
          - stage3
          - stage4
          - prod-lite

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.staging_environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_BACKEND_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_BACKEND_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

    #   - name: Fill in the new image ID in the Amazon ECS task definition web
    #     id: task-def-web
    #     uses: aws-actions/amazon-ecs-render-task-definition@f0e3859cc4f50aa73ee4a2dc82781f8737bcbffd
    #     with:
    #       task-definition-arn: arn:aws:ecs:us-west-1:357844151986:task-definition/fondo-dev-web-app-backend:21
    #       container-name: web-app-backend
    #       image: 357844151986.dkr.ecr.us-west-1.amazonaws.com/fondo/backend:0.0.10

    #   - name: Deploy Amazon ECS task definition web
    #     id: deploy-task-def-web
    #     uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
    #     with:
    #       task-definition: ${{ steps.task-def-web.outputs.task-definition }}
    #       service: ${{ vars.ECS_SERVICE }}
    #       cluster: ${{ vars.ECS_CLUSTER }}
    #       wait-for-service-stability: true

      - name: Fill in the new image ID in the Amazon ECS task definition runonce-scripts
        id: task-def-runonce-scripts
        uses: aws-actions/amazon-ecs-render-task-definition@f0e3859cc4f50aa73ee4a2dc82781f8737bcbffd
        with:
          task-definition-arn: arn:aws:ecs:us-west-1:357844151986:task-definition/fondo-dev-web-app-runonce-scripts:4
          container-name: web-app-runonce-scripts
          image: 357844151986.dkr.ecr.us-west-1.amazonaws.com/fondo/backend:0.0.10

      - name: Run ECS Task for runonce-scripts
        run: |
          aws ecs run-task \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --task-definition ${{ steps.task-def-runonce-scripts.outputs.task-definition }} \
            --launch-type EC2
