name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      staging_environment:
        type: choice
        description: Choose Staging Environment
        options:
          - stage1
          - stage2
          - stage3
          - stage4
          - Production

jobs:
  display-staging-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.staging_environment }}
    steps:
      - name: Display input staging_environment
        run: |
          echo "Selected environment: ${{ inputs.staging_environment }}"
          echo "MYSQL_DATABASE is ${{ vars.MY_DATABASE }}"
          echo "MYSQL_PASSWORD is ${{ secrets.MYSQL_PASSWORD }}"

  deploy-backend:
    uses: ./.github/workflows/test.yaml
    with:
      staging_environment: ${{ inputs.staging_environment }}
    secrets:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

  using-artifact:
    needs: deploy-backend
    uses: ./.github/workflows/using-artifact.yaml
