name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      staging_environment:
        type: choice
        description: Choose Staging Environment
        options:
          - stage1
          - stage2
          - stage3
          - stage4
          - Production

jobs:
  display-staging-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Display input staging_environment
        run: |
          cat ${{ inputs.staging_environment }}

  deploy-backend:
    needs: display-staging-environment
    uses: ./.github/workflows/test.yaml
    with:
      staging_environment: ${{ inputs.staging_environment }}
