name: Secrets and Environment Variables

on:
  workflow_dispatch:

jobs:
  top-env-variables:
    runs-on: ubuntu-latest
    # environment: Production

    steps:
      - name: Read a Variable
        run: |
          echo "Adding environment variables..."
          for var in ${{ vars }}; do
            echo "var"
          done

      - name: Read a Secret
        run: echo "My secret is ${{ secrets.PRODUCTION_SECRET }}"

      - name: Render vars as JSON and save to file
        run: |
          echo '${{ toJSON(vars) }}' > vars.json

      - name: Render secrets as JSON and save to file
        run: |
          echo '${{ toJSON(secrets) }}' > secrets.json

      - name: Create .env file from vars.json
        run: |
          echo "Creating .env file..."
          # Read the JSON and create .env entries
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' vars.json > .env

      - name: Add secrets to .env file
        run: |
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' secrets.json >> .env

      - name: Display .env file contents
        run: |
          cat .env

      - name: Render secrets
        run: |
          echo "${{ toJSON(secrets) }}"
