name: Secrets and Environment Variables

on:
  workflow_dispatch:

jobs:
  top-env-variables:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Read a Variable
        run: echo "My environment varuable is ${{ vars.PROD_VAR }}"

      - name: Read a Secret
        run: echo "My secret is ${{ secrets.PRODUCTION_SECRET }}"