name: Secrets and Environment Variables

on:
  workflow_dispatch:

jobs:
  top-env-variables:
    runs-on: ubuntu-latest
    # environment: Production

    steps:
      - name: Read a Variable
        run: |
          echo "Adding environment variables..."
          for var in ${{ vars }}; do
            echo "${var}"
          done

      - name: Read a Secret
        run: echo "My secret is ${{ secrets.PRODUCTION_SECRET }}"

      - name: Render a vars
        run: |
          echo "${{ toJSON(vars) }}"

      - name: Render secrets
        run: |
          echo "${{ toJSON(secrets) }}"