name: Secrets and Environment Variables

on:
  workflow_dispatch:

jobs:
  top-env-variables:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Read a Variable
        run: |
          export PRODUCTION_VAR=production
          echo "Adding environment variables..."
          for var in $(printenv); do
            echo "$var"
          done

      - name: Read a Secret
        run: echo "My secret is ${{ secrets.PRODUCTION_SECRET }}"